export interface GlossaryLink {
  label: string
  url: string
}

export interface GlossaryEntry {
  term: string
  aliases?: string[]
  definition?: string
  advanced?: string
  context?: string
  links?: GlossaryLink[]
}

export const DEFAULT_GLOSSARY_TERMS: GlossaryEntry[] = [
  {
    term: 'RAG',
    aliases: ['Retrieval-Augmented Generation'],
    definition: '先從知識庫找相關資料，再把資料交給模型回答，降低模型只靠記憶亂猜的機率。',
    advanced: 'RAG 通常包含 chunking、embedding、retrieval、reranking、generation 與 citation/grounding 檢查；品質瓶頸多半在檢索與上下文選擇。',
    context: '常出現在 AI 搜尋、知識庫問答、客服與文件助理。',
    links: [{ label: '站內搜尋 RAG 文章', url: '/search?q=RAG&mode=rag' }],
  },
  {
    term: 'embedding',
    aliases: ['embeddings', '向量嵌入'],
    definition: '把文字轉成一串數字向量，讓系統可以用距離判斷兩段文字語意上像不像。',
    advanced: 'Embedding 模型會把 token 序列投影到高維空間；實務上要同時注意模型語言能力、chunk 粒度、metadata filter 與索引更新。',
    context: '常用在語意搜尋、推薦、去重與 RAG 檢索。',
    links: [{ label: '站內搜尋 embedding', url: '/search?q=embedding&mode=rag' }],
  },
  {
    term: 'Vectorize',
    aliases: ['Cloudflare Vectorize'],
    definition: 'Cloudflare 的向量資料庫服務，用來存 embedding 並做相似度搜尋。',
    advanced: 'Vectorize 負責 ANN 類型的近似向量查詢；在 RAG 中通常還會搭配 D1/FTS 做 hybrid search 與 metadata 補全。',
    context: '這個站的 RAG 檢索使用 Vectorize 存文章與文件 chunk 的向量。',
    links: [{ label: '站內搜尋 Vectorize', url: '/search?q=Vectorize&mode=rag' }],
  },
  {
    term: 'Cloudflare D1',
    aliases: ['D1'],
    definition: 'Cloudflare Workers 上的 serverless SQLite 資料庫。',
    advanced: 'D1 適合邊緣應用的小型關聯式資料；要注意 migration、batch 寫入、索引與 Workers 執行時間限制。',
    context: '本站用 D1 存文章索引、聊天紀錄、RAG 設定與觀測資料。',
    links: [{ label: '站內搜尋 D1', url: '/search?q=Cloudflare%20D1&mode=rag' }],
  },
  {
    term: 'FTS5',
    definition: 'SQLite 的全文搜尋功能，可以用關鍵字與 BM25 分數找文字內容。',
    advanced: 'FTS5 適合 lexical retrieval；與 embedding retrieval 融合時，可以補足專有名詞、錯誤碼、精確字串等語意模型容易漏掉的查詢。',
    context: 'Hybrid search 常把 FTS5 結果和向量搜尋結果一起排序。',
    links: [{ label: 'Hybrid Search：BM25 + 向量搜尋', url: '/posts/ai/2026-03-12-hybrid-search-bm25-vector-rrf' }],
  },
  {
    term: 'BM25',
    definition: '一種關鍵字搜尋排序演算法，會看詞出現頻率、稀有程度和文件長度。',
    advanced: 'BM25 是 lexical retrieval 的常見 baseline；它不理解語意，但對錯誤碼、API 名稱、命令字串很可靠。',
    context: '在 RAG 系統裡常和向量搜尋互補。',
    links: [{ label: 'Hybrid Search：BM25 + 向量搜尋', url: '/posts/ai/2026-03-12-hybrid-search-bm25-vector-rrf' }],
  },
  {
    term: 'reranker',
    aliases: ['Reranker'],
    definition: '第二階段排序器，會重新檢查候選結果，把更相關的內容排前面。',
    advanced: 'Reranker 常用 cross-encoder 或 LLM 對 query-document pair 打分；品質通常更好，但延遲與成本也更高。',
    context: 'RAG 在初步召回很多 chunk 後，會用 reranker 過濾雜訊。',
    links: [{ label: '站內搜尋 reranker', url: '/search?q=reranker&mode=rag' }],
  },
  {
    term: 'MMR',
    aliases: ['Maximal Marginal Relevance'],
    definition: '一種排序方法，會同時考慮相關性和多樣性，避免結果全部長得太像。',
    advanced: 'MMR 會用 lambda 權衡 query relevance 與候選文件之間的相似度；適合多角度問題或容易重複召回的知識庫。',
    context: 'RAG 常用 MMR 讓 Writer 看到更多不同證據。',
    links: [{ label: '站內搜尋 MMR', url: '/search?q=MMR&mode=rag' }],
  },
  {
    term: 'HyDE',
    definition: '先讓模型假想一段可能答案，再用這段答案去搜尋資料。',
    advanced: 'HyDE 可以改善抽象查詢的召回，但也可能把檢索方向帶偏，所以最好用 feature flag 與 eval 控制。',
    context: '常用在使用者問題很短、關鍵字不足或概念性查詢時。',
    links: [{ label: '站內搜尋 HyDE', url: '/search?q=HyDE&mode=rag' }],
  },
  {
    term: 'LangGraph',
    definition: 'LangChain 生態系裡用來編排多步驟 agent / workflow 的框架。',
    advanced: 'LangGraph 把流程表示成 state graph，適合有 planner、research、writer、critic 等節點且需要可觀測狀態轉移的應用。',
    context: '本站聊天系統的 RAG pipeline 支援 LangGraph 與手寫 pipeline 切換。',
    links: [{ label: '站內搜尋 LangGraph', url: '/search?q=LangGraph&mode=rag' }],
  },
  {
    term: 'Astro',
    definition: '一個偏內容網站與多框架整合的前端框架，可以產生靜態頁，也能部署成 server app。',
    advanced: 'Astro 的 islands architecture 讓大部分頁面輸出靜態 HTML，只在需要互動的元件 hydrate JavaScript。',
    context: 'quidproquo.cc 是用 Astro 建的部落格。',
    links: [{ label: '站內搜尋 Astro', url: '/search?q=Astro&mode=rag' }],
  },
  {
    term: 'Cloudflare Workers',
    aliases: ['Workers'],
    definition: 'Cloudflare 的 serverless runtime，可以在邊緣節點執行 JavaScript/TypeScript。',
    advanced: 'Workers 適合低延遲 API、SSR、排程任務與邊緣整合，但要注意 CPU time、binding、streaming 與平台限制。',
    context: '本站的 Astro server output 部署到 Cloudflare Workers。',
    links: [{ label: '站內搜尋 Workers', url: '/search?q=Cloudflare%20Workers&mode=rag' }],
  },
  {
    term: 'LLM',
    aliases: ['Large Language Model', '大型語言模型'],
    definition: '能理解與生成文字的 AI 模型，常用來回答問題、摘要、改寫與產生內容。',
    advanced: 'LLM 的輸出品質會受到 prompt、context window、訓練資料、推理設定與外部工具結果影響；在產品中通常要搭配檢索、評估與觀測。',
    context: '本站常討論 LLM 在內容系統、RAG、agent workflow 與產品設計中的用法。',
    links: [{ label: '站內搜尋 LLM', url: '/search?q=LLM&mode=rag' }],
  },
  {
    term: 'AI Agent',
    aliases: ['agent', 'agents', 'AI agents'],
    definition: '能根據目標自主拆解步驟、使用工具並持續推進任務的 AI 系統。',
    advanced: 'Agent 通常包含 planner、tool use、memory、reflection 或 evaluator；實務重點是邊界、觀測、權限與失敗時的人工接管。',
    context: '本站用它討論內容生產、研究流程、RAG 管線與多代理協作。',
    links: [{ label: '站內搜尋 AI Agent', url: '/search?q=AI%20Agent&mode=rag' }],
  },
  {
    term: 'token',
    aliases: ['tokens'],
    definition: '模型讀寫文字時使用的基本單位，可以是一個字、一段字或標點。',
    advanced: 'Token 數會影響成本、延遲與可放入 context window 的資訊量；不同模型與 tokenizer 對同一段文字的切分可能不同。',
    context: '討論 LLM 成本、上下文長度、RAG chunk 與 prompt 設計時常會用到。',
    links: [{ label: '站內搜尋 token', url: '/search?q=token&mode=rag' }],
  },
  {
    term: 'context window',
    aliases: ['上下文視窗'],
    definition: '模型一次能讀進去的文字容量上限。',
    advanced: 'Context window 越大不代表品質一定越好；長上下文仍需要選材、排序、摘要與去雜訊，否則模型可能忽略關鍵證據。',
    context: '常用來討論 RAG 要塞多少資料、agent 要保留多少歷史，以及長文處理策略。',
    links: [{ label: '站內搜尋 context window', url: '/search?q=context%20window&mode=rag' }],
  },
  {
    term: 'eval',
    aliases: ['evaluation', '評估'],
    definition: '用固定問題、資料與指標檢查系統改動是否真的變好。',
    advanced: 'RAG 與 agent eval 常看 retrieval recall、answer faithfulness、citation accuracy、latency 與成本；好的 eval 會先針對觀察到的失敗案例設計。',
    context: '本站強調 RAG 與 AI 功能要用 eval 驗證，而不是只靠主觀試用。',
    links: [{ label: '站內搜尋 eval', url: '/search?q=eval&mode=rag' }],
  },
  {
    term: 'pipeline',
    aliases: ['workflow'],
    definition: '把一連串處理步驟串起來，讓資料或任務可以穩定地從輸入走到輸出。',
    advanced: 'AI pipeline 常包含資料清理、檢索、模型呼叫、後處理、評估與觀測；每個節點都應該能被單獨測試與替換。',
    context: '本站常用 pipeline 描述內容生產、搜尋索引、RAG 與 agent 編排。',
    links: [{ label: '站內搜尋 pipeline', url: '/search?q=pipeline&mode=rag' }],
  },
  {
    term: 'metadata',
    aliases: ['frontmatter'],
    definition: '描述內容的結構化資料，例如標題、日期、標籤、分類或語言。',
    advanced: 'Metadata 能支援篩選、排序、SEO、推薦與 RAG 檢索；品質不穩會讓搜尋、索引與內容營運流程變脆弱。',
    context: '本站文章用 frontmatter 管理 metadata，並把它同步到搜尋與內容工具。',
    links: [{ label: '站內搜尋 metadata', url: '/search?q=metadata&mode=rag' }],
  },
  {
    term: 'Pagefind',
    definition: '一個靜態網站全文搜尋工具，會在 build 後建立前端可查詢的搜尋索引。',
    advanced: 'Pagefind 適合內容站的低維運搜尋；和 RAG 相比，它更穩定、便宜，也更適合精確關鍵字查詢。',
    context: '本站用 Pagefind 提供傳統全文搜尋，和 RAG 搜尋互補。',
    links: [{ label: '站內搜尋 Pagefind', url: '/search?q=Pagefind&mode=rag' }],
  },
  {
    term: 'AEO',
    aliases: ['Answer Engine Optimization'],
    definition: '讓內容更容易被 AI 搜尋或答案引擎理解、引用與回答的內容優化方法。',
    advanced: 'AEO 會重視清楚問題、直接答案、結構化段落、可信來源與可引用語句；它和 SEO 重疊，但更偏向答案抽取。',
    context: '本站的行銷文章會用 AEO 討論 AI 搜尋時代的內容策略。',
    links: [{ label: '站內搜尋 AEO', url: '/search?q=AEO&mode=rag' }],
  },
  {
    term: 'GEO',
    aliases: ['Generative Engine Optimization'],
    definition: '針對生成式搜尋與 AI 回答系統設計內容，讓品牌或觀點更容易被生成答案採用。',
    advanced: 'GEO 通常關注實體一致性、權威訊號、引用友善內容、跨平台提及與答案覆蓋率追蹤。',
    context: '本站用 GEO 討論 AI 搜尋環境下的內容與品牌能見度。',
    links: [{ label: '站內搜尋 GEO', url: '/search?q=GEO&mode=rag' }],
  },
  {
    term: 'Docker',
    aliases: ['docker compose', 'Compose'],
    definition: '把應用程式和它需要的環境包成容器，讓本機、伺服器和 CI 更容易跑出一致結果。',
    advanced: 'Docker 的關鍵取捨在 image 建置、volume、network、DNS、權限與安全掃描；Compose 則常用來管理多容器開發或小型部署。',
    context: '本站的技術文章常用 Docker 說明部署、nginx、502 與容器網路問題。',
    links: [{ label: '站內搜尋 Docker', url: '/search?q=Docker&mode=rag' }],
  },
  {
    term: 'nginx',
    aliases: ['reverse proxy'],
    definition: '常見的網頁伺服器與反向代理，可以把外部請求轉發到不同後端服務。',
    advanced: 'nginx 常見設定包含 upstream、server block、location、proxy headers、TLS、reload 與 syntax check；反向代理問題常出在 DNS、port、container network 或 header。',
    context: '本站多篇 debug 文章用 nginx 分析 502、conf.d 拆分與多服務代理。',
    links: [{ label: '站內搜尋 nginx', url: '/search?q=nginx&mode=rag' }],
  },
  {
    term: 'DNS',
    aliases: ['domain name system'],
    definition: '把網域名稱轉成機器能連線的位址或服務名稱。',
    advanced: '在 Docker 與 nginx 場景中，DNS 可能指向容器名稱、network alias 或外部網域；解析範圍和網路邊界錯了就會造成 502 或連線失敗。',
    context: '本站用 DNS 說明跨 Compose 專案、Cloudflare origin 與 reverse proxy 的排錯。',
    links: [{ label: '站內搜尋 DNS', url: '/search?q=DNS&mode=rag' }],
  },
  {
    term: 'Git',
    aliases: ['Git Conditional Includes', 'conditional includes'],
    definition: '分散式版本控制工具，用來追蹤程式碼變更與協作。',
    advanced: 'Git Conditional Includes 可以依照 repository 路徑載入不同設定，適合分開管理個人與工作帳號、簽章或 SSH identity。',
    context: '本站用 Git 討論多帳號設定、工作流程與專案管理。',
    links: [{ label: '站內搜尋 Git', url: '/search?q=Git&mode=rag' }],
  },
  {
    term: 'MCP',
    aliases: ['Model Context Protocol', 'MCP Server'],
    definition: '一種讓 AI 工具連接外部資料、工具與服務的協定。',
    advanced: 'MCP 把 tool、resource、prompt 等能力用標準介面暴露給 client；安全上要注意權限、資料外流、工具副作用與審計。',
    context: '本站用 MCP 討論 Claude Code 與外部工具整合。',
    links: [{ label: '站內搜尋 MCP', url: '/search?q=MCP&mode=rag' }],
  },
  {
    term: 'React Hook Form',
    aliases: ['Zod', 'validation'],
    definition: 'React Hook Form 管理表單狀態，Zod 負責用 schema 驗證資料。',
    advanced: '兩者搭配時可以把 runtime validation 和 TypeScript 型別推導接起來，降低前後端表單規則漂移；但 schema 共用仍要注意資料邊界與錯誤訊息設計。',
    context: '本站用它說明表單處理、型別安全與 monorepo schema 共用。',
    links: [{ label: '站內搜尋 React Hook Form', url: '/search?q=React%20Hook%20Form&mode=rag' }],
  },
  {
    term: 'ClickHouse',
    aliases: ['OLAP', 'OLTP'],
    definition: 'ClickHouse 是偏分析查詢的欄導向資料庫，適合大量事件、日誌與指標聚合。',
    advanced: 'ClickHouse 用欄導向儲存、壓縮、向量化執行與 MergeTree engine 提升聚合查詢效率；常和 PostgreSQL 這類 OLTP 資料庫分工。',
    context: '本站用 ClickHouse 說明產品分析、事件資料與 AI 推薦特徵工程。',
    links: [{ label: '站內搜尋 ClickHouse', url: '/search?q=ClickHouse&mode=rag' }],
  },
  {
    term: 'Prisma',
    aliases: ['Prisma ORM', 'ORM'],
    definition: 'Prisma 是 TypeScript 專案常用的 ORM，能用 schema 產生型別安全的資料庫 client。',
    advanced: 'Prisma 把 schema、migration 與 query client 串在一起，降低手寫 SQL 與型別維護成本；代價是需要理解抽象層與複雜查詢限制。',
    context: '本站用 Prisma 討論 TypeScript 後端、資料庫 migration 與 schema-first 開發。',
    links: [{ label: '站內搜尋 Prisma', url: '/search?q=Prisma&mode=rag' }],
  },
  {
    term: 'TanStack Query',
    aliases: ['React Query', 'server state'],
    definition: 'React 生態中管理 server state 的工具，負責資料 fetch、快取、重新驗證與 loading/error 狀態。',
    advanced: 'TanStack Query 把 query key、cache invalidation、mutation、background refetch 與 request dedupe 包成一致模型，適合取代手寫 useEffect fetching。',
    context: '本站用 TanStack Query 說明前端資料取得、快取與 UI state 的分工。',
    links: [{ label: '站內搜尋 TanStack Query', url: '/search?q=TanStack%20Query&mode=rag' }],
  },
  {
    term: 'Slack',
    aliases: ['Slack integration'],
    definition: '團隊溝通工具，也常被拿來接收系統通知或觸發工作流程。',
    advanced: 'Slack integration 通常包含 app、bot token、webhook、OAuth scope 與事件訂閱；導入 AI 工具時要特別注意權限與訊息可見範圍。',
    context: '本站用 Slack 討論 Claude Code 遠端控制、通知與團隊工作流整合。',
    links: [{ label: '站內搜尋 Slack', url: '/search?q=Slack&mode=rag' }],
  },
  {
    term: 'API',
    aliases: ['Application Programming Interface'],
    definition: '程式之間溝通的介面，讓一個系統可以用固定格式呼叫另一個系統的功能或資料。',
    advanced: 'API 設計要處理認證、版本、錯誤格式、rate limit、資料 schema 與相容性；在 AI 產品裡常是模型、工具與前後端之間的邊界。',
    context: '本站常用 API 討論模型呼叫、工具整合、後端服務與 agent tool interface。',
    links: [{ label: '站內搜尋 API', url: '/search?q=API&mode=rag' }],
  },
  {
    term: 'CLI',
    aliases: ['command-line interface'],
    definition: '用終端機指令操作工具的介面。',
    advanced: 'CLI 適合自動化、腳本化與遠端環境；agentic coding 工具常把 CLI 當成模型執行任務、讀寫檔案與跑測試的主要操作層。',
    context: '本站大量討論 Claude Code、Codex、Gemini CLI、opencode 等終端機 AI 工具。',
    links: [{ label: '站內搜尋 CLI', url: '/search?q=CLI&mode=rag' }],
  },
  {
    term: 'SDK',
    aliases: ['Software Development Kit'],
    definition: '給開發者使用的工具包，通常包含 client library、型別、範例與文件。',
    advanced: 'SDK 會把 API 的低階細節包起來，但也可能限制可控性；選用時要看版本穩定度、錯誤處理、串流支援與 runtime 相容性。',
    context: '本站用 SDK 討論 OpenAI、LangChain、Cloudflare 與各種模型服務整合。',
    links: [{ label: '站內搜尋 SDK', url: '/search?q=SDK&mode=rag' }],
  },
  {
    term: 'JSON',
    definition: '常見的文字資料格式，用 key-value 結構表示物件、陣列、字串與數字。',
    advanced: 'JSON 易讀、跨語言支援好，但缺少註解與強 schema；在 AI 工具呼叫、API response、設定檔與結構化輸出中都很常見。',
    context: '本站常用 JSON 討論設定、工具輸入輸出、模型結構化回答與前後端資料交換。',
    links: [{ label: '站內搜尋 JSON', url: '/search?q=JSON&mode=rag' }],
  },
  {
    term: 'YAML',
    definition: '偏人類可讀的設定檔格式，常用縮排表示層級。',
    advanced: 'YAML 適合寫部署、CI 與 agent 設定，但縮排、型別自動轉換與多文件語法容易造成隱性錯誤。',
    context: '本站用 YAML 討論 GitHub Actions、agent 設定、部署與工作流程描述。',
    links: [{ label: '站內搜尋 YAML', url: '/search?q=YAML&mode=rag' }],
  },
  {
    term: 'HTTP',
    definition: '瀏覽器、API 與伺服器交換請求和回應的網路協定。',
    advanced: '實務排錯常看 method、status code、header、body、cache、redirect、CORS 與 proxy 行為；AI tool 與 MCP server 也常透過 HTTP 暴露服務。',
    context: '本站用 HTTP 討論 API、Cloudflare Workers、nginx、SSE 串流與遠端 agent。',
    links: [{ label: '站內搜尋 HTTP', url: '/search?q=HTTP&mode=rag' }],
  },
  {
    term: 'SQL',
    definition: '操作關聯式資料庫的查詢語言，用來查詢、篩選、聚合與更新資料。',
    advanced: 'SQL 品質會影響效能與正確性；在 RAG 與內容站裡常和 FTS、metadata filter、migration、index 與資料同步一起出現。',
    context: '本站用 SQL 討論 D1、SQLite、ClickHouse、Text-to-SQL 與資料管線。',
    links: [{ label: '站內搜尋 SQL', url: '/search?q=SQL&mode=rag' }],
  },
  {
    term: 'SSH',
    definition: '安全連線到遠端機器的協定，常用來登入伺服器、傳檔或跑遠端指令。',
    advanced: 'SSH 常見設定包含 key pair、config alias、known_hosts、agent forwarding 與 port forwarding；多帳號環境要特別注意 identity 選擇。',
    context: '本站用 SSH 討論遠端開發、伺服器維護、scp 與多帳號 Git 設定。',
    links: [{ label: '站內搜尋 SSH', url: '/search?q=SSH&mode=rag' }],
  },
  {
    term: 'GPU',
    definition: '擅長大量平行運算的處理器，常用在模型訓練、推理與圖形運算。',
    advanced: 'LLM 推理會受 GPU 記憶體、頻寬、tensor core、量化格式與 batch size 影響；本機部署時 VRAM 通常比純算力更早成為瓶頸。',
    context: '本站用 GPU 討論本機 LLM、NVIDIA DGX Spark、vLLM、llama.cpp 與推理成本。',
    links: [{ label: '站內搜尋 GPU', url: '/search?q=GPU&mode=rag' }],
  },
  {
    term: 'CPU',
    definition: '通用處理器，負責執行程式的大部分一般運算。',
    advanced: 'CPU 推理通常比 GPU 慢，但部署簡單、成本低；效能會受核心數、記憶體頻寬、SIMD 指令與量化格式影響。',
    context: '本站在本機模型、Workers 限制、容器與效能排錯文章中常提到 CPU。',
    links: [{ label: '站內搜尋 CPU', url: '/search?q=CPU&mode=rag' }],
  },
  {
    term: 'Cloudflare KV',
    aliases: ['KV'],
    definition: 'Cloudflare 的 key-value 儲存服務，適合存小型設定、快取與讀多寫少資料。',
    advanced: 'KV 是 eventual consistency，讀取快但不適合強一致交易；要和 D1、R2、Durable Objects 依資料型態分工。',
    context: '本站用 KV 討論 Cloudflare 架構、快取與邊緣儲存選型。',
    links: [{ label: '站內搜尋 Cloudflare KV', url: '/search?q=Cloudflare%20KV&mode=rag' }],
  },
  {
    term: 'Cloudflare R2',
    aliases: ['R2'],
    definition: 'Cloudflare 的物件儲存服務，類似 S3，適合存圖片、檔案、備份與大型內容。',
    advanced: 'R2 沒有 egress fee 的定位讓它適合內容分發與資料湖邊界；使用時仍要設計 bucket 權限、快取、metadata 與生命週期。',
    context: '本站用 R2 討論物件儲存、靜態資產、Workers 整合與 S3 相容 API。',
    links: [{ label: '站內搜尋 Cloudflare R2', url: '/search?q=Cloudflare%20R2&mode=rag' }],
  },
  {
    term: 'CI/CD',
    aliases: ['CI'],
    definition: '把測試、建置與部署流程自動化，讓程式碼變更能穩定交付。',
    advanced: 'CI 偏向自動測試與驗證，CD 偏向自動發布；好的 pipeline 會把 lint、test、build、安全掃描、preview 與 rollback 都納入。',
    context: '本站用 CI/CD 討論 GitHub Actions、Claude Code 自動化、部署與 agent 開發流程。',
    links: [{ label: '站內搜尋 CI/CD', url: '/search?q=CI%2FCD&mode=rag' }],
  },
  {
    term: 'PR',
    aliases: ['pull request'],
    definition: '把一組程式碼變更送出審查與合併的協作單位。',
    advanced: '高品質 PR 會包含清楚範圍、測試證據、風險說明與可審查的 diff；AI code review pipeline 通常也是以 PR 為主要輸入。',
    context: '本站用 PR 討論 code review、GitHub Actions、多人協作與 AI 開發流程。',
    links: [{ label: '站內搜尋 PR', url: '/search?q=PR&mode=rag' }],
  },
  {
    term: 'IDE',
    definition: '整合程式碼編輯、搜尋、除錯、終端機與專案工具的開發環境。',
    advanced: 'AI coding agent 進入 IDE 後，會影響 context 收集、檔案操作、diff review 與人機協作節奏；和純 CLI 工具的權限邊界不同。',
    context: '本站用 IDE 討論 Cursor、Kiro、Warp、agentic development environment 與 coding assistant。',
    links: [{ label: '站內搜尋 IDE', url: '/search?q=IDE&mode=rag' }],
  },
  {
    term: 'TUI',
    aliases: ['terminal UI'],
    definition: '在終端機裡呈現互動式介面的程式。',
    advanced: 'TUI 介於純文字 CLI 與圖形 IDE 之間，適合鍵盤操作、遠端環境與 agent 工作流；但要處理畫面更新、輸入焦點與日誌可讀性。',
    context: '本站用 TUI 討論 Claude Code、Codex CLI、opencode 與終端機 agent 體驗。',
    links: [{ label: '站內搜尋 TUI', url: '/search?q=TUI&mode=rag' }],
  },
  {
    term: 'OCR',
    aliases: ['Optical Character Recognition'],
    definition: '把圖片或掃描文件中的文字辨識成可搜尋、可處理的文字。',
    advanced: 'OCR 品質受解析度、版面、語言、表格、手寫字與壓縮影響；在 RAG 裡常需要搭配版面切分、校正與 citation 對齊。',
    context: '本站用 OCR 討論文件理解、DeepSeek-OCR、PageIndex 與向量化前的資料處理。',
    links: [{ label: '站內搜尋 OCR', url: '/search?q=OCR&mode=rag' }],
  },
  {
    term: 'SSE',
    aliases: ['Server-Sent Events'],
    definition: '伺服器用單向串流把事件持續推給瀏覽器的 HTTP 機制。',
    advanced: 'SSE 比 WebSocket 簡單，適合模型 token streaming、進度回報與通知；要注意 proxy buffering、timeout、重連與事件格式。',
    context: '本站用 SSE 討論 RAG streaming、聊天 UI 與 Workers 上的串流回應。',
    links: [{ label: '站內搜尋 SSE', url: '/search?q=SSE&mode=rag' }],
  },
  {
    term: 'TTL',
    aliases: ['time to live'],
    definition: '資料、快取或 token 保留多久才過期的時間設定。',
    advanced: 'TTL 太短會造成重算與 cache miss，太長會讓資料過期或權限延遲失效；常和 cache、session、rate limit、trace retention 一起設計。',
    context: '本站用 TTL 討論快取、RAG trace 保留、token 配額與系統資料生命週期。',
    links: [{ label: '站內搜尋 TTL', url: '/search?q=TTL&mode=rag' }],
  },
  {
    term: 'RRF',
    aliases: ['Reciprocal Rank Fusion'],
    definition: '把多個排序結果融合的演算法，重點看每個結果在各來源中的排名。',
    advanced: 'RRF 不需要不同 retriever 的分數可比較，只要用排名就能融合 BM25、向量搜尋與其他召回來源；常用在 hybrid search。',
    context: '本站用 RRF 討論 BM25 + vector 的 RAG 檢索融合。',
    links: [{ label: '站內搜尋 RRF', url: '/search?q=RRF&mode=rag' }],
  },
  {
    term: 'SPLADE',
    definition: '一種 sparse retrieval 方法，讓模型產生可解釋的稀疏詞權重，用來做語意化關鍵字搜尋。',
    advanced: 'SPLADE 介於傳統 lexical retrieval 與 dense embedding 之間，能保留倒排索引效率，也能用模型學到查詢與文件的詞彙擴展。',
    context: '本站用 SPLADE 討論 advanced RAG、稀疏向量與 hybrid retrieval。',
    links: [{ label: '站內搜尋 SPLADE', url: '/search?q=SPLADE&mode=rag' }],
  },
  {
    term: 'BGE-M3',
    aliases: ['BGE M3'],
    definition: 'BAAI 推出的多語、多功能 embedding 模型，支援 dense、sparse 與 multi-vector 表示。',
    advanced: 'BGE-M3 常被用來做多語 RAG 與 hybrid retrieval；選用時要評估語言覆蓋、向量維度、推理成本與和既有索引的相容性。',
    context: '本站用 BGE-M3 討論 embedding model selection 與中文/多語 RAG。',
    links: [{ label: '站內搜尋 BGE-M3', url: '/search?q=BGE-M3&mode=rag' }],
  },
  {
    term: 'GGUF',
    definition: '本機 LLM 常用的模型檔案格式，特別常見於 llama.cpp 生態。',
    advanced: 'GGUF 會封裝模型權重與 metadata，並支援多種量化版本；下載時要依硬體 VRAM/RAM、速度與品質取捨選 Q4、Q5、Q8 等格式。',
    context: '本站用 GGUF 討論 Ollama、llama.cpp、本機推理與小模型部署。',
    links: [{ label: '站內搜尋 GGUF', url: '/search?q=GGUF&mode=rag' }],
  },
  {
    term: 'JSON-LD',
    definition: '用 JSON 表示 linked data 的格式，常用來在網頁中提供結構化資料。',
    advanced: 'JSON-LD 常搭配 Schema.org，讓搜尋引擎與 AI crawler 更容易理解文章、產品、FAQ 或組織資訊；內容要和頁面可見內容一致。',
    context: '本站用 JSON-LD 討論 SEO、AEO/GEO 與內容可被機器理解的程度。',
    links: [{ label: '站內搜尋 JSON-LD', url: '/search?q=JSON-LD&mode=rag' }],
  },
  {
    term: 'SSR',
    aliases: ['server-side rendering'],
    definition: '在伺服器端先產生 HTML，再送到瀏覽器顯示的渲染方式。',
    advanced: 'SSR 可以改善首屏速度與 SEO，但會引入 runtime、cache、streaming、hydration 與部署平台限制；Astro、Next.js、Workers 都有不同取捨。',
    context: '本站用 SSR 討論 Astro、Cloudflare Workers、Next.js 與內容網站部署。',
    links: [{ label: '站內搜尋 SSR', url: '/search?q=SSR&mode=rag' }],
  },
  {
    term: 'MDX',
    definition: '可以在 Markdown 裡嵌入 JSX 元件的內容格式。',
    advanced: 'MDX 適合互動式文件與內容元件化，但會增加編譯、樣式範圍、元件依賴與安全邊界的複雜度。',
    context: '本站用 MDX 討論 Astro 內容系統、scoped CSS 與部落格模板。',
    links: [{ label: '站內搜尋 MDX', url: '/search?q=MDX&mode=rag' }],
  },
  {
    term: 'REST',
    aliases: ['REST API'],
    definition: '一種常見 API 設計風格，通常用 HTTP method 與 URL 表示資源操作。',
    advanced: 'REST 的重點是資源模型、狀態碼、無狀態請求與快取語意；和 GraphQL、RPC 或 tool-call 介面相比，適合清楚的 CRUD 型服務。',
    context: '本站用 REST 討論 API 設計、MCP/CLI/API 介面比較與後端整合。',
    links: [{ label: '站內搜尋 REST', url: '/search?q=REST&mode=rag' }],
  },
  {
    term: 'CUDA',
    definition: 'NVIDIA 的 GPU 平行運算平台與程式設計模型。',
    advanced: '許多深度學習框架、推理引擎與量化工具依賴 CUDA 生態；部署時常要對齊 driver、CUDA runtime、模型格式與硬體能力。',
    context: '本站用 CUDA 討論本機 LLM、vLLM、GPU 推理與 AI hardware。',
    links: [{ label: '站內搜尋 CUDA', url: '/search?q=CUDA&mode=rag' }],
  },
  {
    term: 'VRAM',
    definition: 'GPU 上的顯示記憶體，模型推理時用來放權重、KV cache 與中間張量。',
    advanced: 'VRAM 決定能跑多大的模型、context window 與 batch size；量化、offload 與 KV cache 壓縮都是在處理 VRAM 壓力。',
    context: '本站用 VRAM 討論本機推理、llama.cpp、vLLM、GPU 選型與小模型部署。',
    links: [{ label: '站內搜尋 VRAM', url: '/search?q=VRAM&mode=rag' }],
  },
  {
    term: 'RAGAS',
    definition: '一套用來評估 RAG 系統回答品質與檢索品質的評估工具。',
    advanced: 'RAGAS 常見指標包含 faithfulness、answer relevancy、context precision 與 context recall；實務上仍要搭配人工標註集與產品情境校準。',
    context: '本站用 RAGAS 討論 RAG evaluation framework 與品質觀測。',
    links: [{ label: '站內搜尋 RAGAS', url: '/search?q=RAGAS&mode=rag' }],
  },
  {
    term: 'DAG',
    aliases: ['directed acyclic graph'],
    definition: '有方向且不會形成循環的圖，常用來表示任務或資料處理的依賴順序。',
    advanced: 'DAG 適合描述可重試、可觀測、可平行化的 pipeline；在 agent workflow 裡可以避免流程互相繞回導致狀態難追。',
    context: '本站用 DAG 討論 workflow、LangGraph、資料管線與多步驟 agent 編排。',
    links: [{ label: '站內搜尋 DAG', url: '/search?q=DAG&mode=rag' }],
  },
  {
    term: 'S3',
    definition: 'Amazon 的物件儲存服務，也常被當成物件儲存 API 相容性的代稱。',
    advanced: 'S3 型儲存適合放大型檔案與非關聯式物件；設計時要處理 bucket、object key、權限、presigned URL、版本與生命週期。',
    context: '本站用 S3 討論 R2、物件儲存、檔案上傳與雲端儲存選型。',
    links: [{ label: '站內搜尋 S3', url: '/search?q=S3&mode=rag' }],
  },
  {
    term: 'prompt',
    aliases: ['prompt engineering'],
    definition: '給模型的任務指令與上下文，會影響模型怎麼理解問題、使用資料與產生答案。',
    advanced: 'Prompt engineering 不只是改文字，還包含輸入結構、範例、約束、輸出格式、錯誤處理與和工具結果的銜接。',
    context: '本站用 prompt 討論聊天系統、RAG、agent workflow、內容產製與模型行為控制。',
    links: [{ label: '站內搜尋 prompt', url: '/search?q=prompt&mode=rag' }],
  },
  {
    term: 'context engineering',
    aliases: ['Context Engineering'],
    definition: '設計模型在每次執行時能看到哪些資訊、順序、格式與工具結果。',
    advanced: 'Context engineering 會處理資料選擇、壓縮、排序、記憶、工具輸出、長上下文與失敗回復；它比單次 prompt 更接近系統設計。',
    context: '本站用 context engineering 討論 agent、RAG、coding assistant 與長任務協作。',
    links: [{ label: '站內搜尋 context engineering', url: '/search?q=context%20engineering&mode=rag' }],
  },
  {
    term: 'function calling',
    aliases: ['tool calling', 'tool use'],
    definition: '讓模型用結構化格式呼叫外部工具，例如查資料、寫檔案、送 API 或執行查詢。',
    advanced: 'Function calling 的重點在 schema 設計、參數驗證、權限邊界、錯誤回傳與工具結果如何放回 context；不是讓模型直接任意執行程式。',
    context: '本站用 function calling 討論 agent tool interface、MCP、API/CLI 比較與自動化工作流。',
    links: [{ label: '站內搜尋 function calling', url: '/search?q=function%20calling&mode=rag' }],
  },
  {
    term: 'fine-tuning',
    aliases: ['fine tuning'],
    definition: '用特定資料再訓練模型，讓它更適合某種任務、格式或風格。',
    advanced: 'Fine-tuning 適合改行為與輸出分布，不適合當成動態知識庫；需要和 RAG、prompt、eval、資料治理一起取捨。',
    context: '本站用 fine-tuning 比較 RAG、模型客製化與產品化 AI 系統的成本。',
    links: [{ label: '站內搜尋 fine-tuning', url: '/search?q=fine-tuning&mode=rag' }],
  },
  {
    term: 'inference',
    aliases: ['推理'],
    definition: '模型拿輸入產生輸出的執行過程。',
    advanced: 'Inference 成本與速度會受模型大小、batching、量化、KV cache、硬體、context 長度與串流策略影響。',
    context: '本站用 inference 討論本機模型、GPU/CPU、vLLM、llama.cpp、雲端模型與延遲成本。',
    links: [{ label: '站內搜尋 inference', url: '/search?q=inference&mode=rag' }],
  },
  {
    term: 'latency',
    definition: '系統從收到請求到回應可用結果之間的等待時間。',
    advanced: 'AI latency 通常拆成檢索時間、首 token 時間、生成速度、工具呼叫、網路與排隊；優化時要分段量測。',
    context: '本站用 latency 討論 RAG 搜尋、模型推理、串流回應與 agent 體驗。',
    links: [{ label: '站內搜尋 latency', url: '/search?q=latency&mode=rag' }],
  },
  {
    term: 'observability',
    aliases: ['tracing'],
    definition: '讓系統的輸入、輸出、耗時、錯誤與中間步驟可以被追蹤和分析。',
    advanced: 'LLM observability 常記錄 prompt、retrieval results、tool calls、token usage、latency、cost 與評估結果；要同時注意隱私與資料保留。',
    context: '本站用 observability 討論 RAG 品質、Langfuse、trace retention、agent debugging 與 eval。',
    links: [{ label: '站內搜尋 observability', url: '/search?q=observability&mode=rag' }],
  },
  {
    term: 'citation',
    aliases: ['grounding'],
    definition: '把回答連回來源資料，讓讀者能檢查答案根據哪裡來。',
    advanced: 'Citation 品質不只看有沒有連結，還要看引用段落是否真的支持答案；RAG 系統常用 grounding 檢查降低幻覺。',
    context: '本站用 citation/grounding 討論 RAG 回答可信度、知識庫問答與內容來源。',
    links: [{ label: '站內搜尋 citation', url: '/search?q=citation&mode=rag' }],
  },
  {
    term: 'chunking',
    definition: '把長文件切成較小片段，方便建立索引、檢索與放進模型上下文。',
    advanced: 'Chunking 要平衡語意完整度、長度、overlap、metadata 與引用精度；切太碎會失去上下文，切太大會增加噪音與成本。',
    context: '本站用 chunking 討論 RAG pipeline、文件處理、embedding 與檢索品質。',
    links: [{ label: '站內搜尋 chunking', url: '/search?q=chunking&mode=rag' }],
  },
  {
    term: 'hybrid search',
    aliases: ['hybrid retrieval'],
    definition: '同時使用關鍵字搜尋與向量搜尋，再把結果融合排序。',
    advanced: 'Hybrid search 常用 BM25/FTS 補精確詞，embedding 補語意相似，最後用 RRF、reranker 或自訂權重融合。',
    context: '本站用 hybrid search 討論 RAG 搜尋品質、BM25、Vectorize、FTS5 與 RRF。',
    links: [{ label: 'Hybrid Search：BM25 + 向量搜尋', url: '/posts/ai/2026-03-12-hybrid-search-bm25-vector-rrf' }],
  },
  {
    term: 'vector database',
    aliases: ['向量資料庫'],
    definition: '專門儲存向量並做相似度搜尋的資料庫或索引系統。',
    advanced: 'Vector database 通常提供 ANN search、metadata filter、namespace、upsert/delete 與索引調參；RAG 中仍需要和原文儲存、權限與 reranking 配合。',
    context: '本站用 vector database 討論 Vectorize、embedding、RAG 架構與資料庫選型。',
    links: [{ label: '站內搜尋 vector database', url: '/search?q=vector%20database&mode=rag' }],
  },
  {
    term: 'cross-encoder',
    aliases: ['cross encoder'],
    definition: '同時讀入 query 和候選文件後直接評分的模型，常用來做 reranking。',
    advanced: 'Cross-encoder 比單純向量相似度更會判斷細節相關性，但需要逐筆候選計算，延遲與成本較高。',
    context: '本站用 cross-encoder 討論 reranker、RAG 檢索品質與候選排序。',
    links: [{ label: '站內搜尋 cross-encoder', url: '/search?q=cross-encoder&mode=rag' }],
  },
  {
    term: 'multi-agent',
    aliases: ['multi agent', '多代理'],
    definition: '把任務拆給多個 agent 或角色協作，而不是只靠單一模型流程完成。',
    advanced: 'Multi-agent 的價值在分工、平行化與交叉檢查，但也會增加協調成本、狀態同步、權限管理與錯誤累積。',
    context: '本站用 multi-agent 討論 coding agent、RAG、Google/Claude patterns 與團隊式 AI 工作流。',
    links: [{ label: '站內搜尋 multi-agent', url: '/search?q=multi-agent&mode=rag' }],
  },
  {
    term: 'subagent',
    aliases: ['sub-agent'],
    definition: '主 agent 派出去處理特定子任務的輔助 agent。',
    advanced: 'Subagent 適合處理可平行、邊界清楚的探索或實作任務；設計時要避免重複工作、衝突寫檔與缺乏整合責任。',
    context: '本站用 subagent 討論 Claude Code、Codex、多代理工作流與 parallel execution。',
    links: [{ label: '站內搜尋 subagent', url: '/search?q=subagent&mode=rag' }],
  },
  {
    term: 'sandbox',
    definition: '限制程式或 agent 能讀寫、執行與連網範圍的隔離環境。',
    advanced: 'Sandbox 能降低工具誤用與供應鏈風險，但會影響測試、依賴安裝、瀏覽器操作與部署流程；需要搭配權限升級與審計。',
    context: '本站用 sandbox 討論 Claude Code devcontainer、OpenAI Codex、OpenClaw 與遠端 agent 安全。',
    links: [{ label: '站內搜尋 sandbox', url: '/search?q=sandbox&mode=rag' }],
  },
  {
    term: 'guardrails',
    definition: '限制、檢查或修正 AI 系統行為的安全與品質機制。',
    advanced: 'Guardrails 可以放在輸入、檢索、工具呼叫、輸出、權限與人工審核層；好的設計會針對具體失敗模式，而不是只靠一段安全提示詞。',
    context: '本站用 guardrails 討論 RAG、agent 安全、內容品質與產品化 AI。',
    links: [{ label: '站內搜尋 guardrails', url: '/search?q=guardrails&mode=rag' }],
  },
  {
    term: 'rate limit',
    aliases: ['rate limiting'],
    definition: '限制一段時間內可以發出多少請求或消耗多少資源。',
    advanced: 'Rate limit 常用來保護成本、穩定性與公平使用；AI 系統通常還要同時追蹤 token、併發、模型配額與重試策略。',
    context: '本站用 rate limit 討論 API、模型服務、RAG token quota、Cloudflare 與 agent 工具呼叫。',
    links: [{ label: '站內搜尋 rate limit', url: '/search?q=rate%20limit&mode=rag' }],
  },
  {
    term: 'webhook',
    definition: '某個事件發生時，由系統主動呼叫另一個 URL 來通知或觸發流程。',
    advanced: 'Webhook 設計要處理簽章驗證、重試、idempotency、逾時、事件版本與 dead-letter；它常是自動化 workflow 的入口。',
    context: '本站用 webhook 討論 agent automation、GitHub/Slack 整合、cron 與事件通知。',
    links: [{ label: '站內搜尋 webhook', url: '/search?q=webhook&mode=rag' }],
  },
  {
    term: 'cron',
    aliases: ['scheduled task'],
    definition: '按照固定時間排程執行的任務。',
    advanced: 'Cron 適合週期性同步、清理、報表與檢查；在 serverless 環境要注意重入、逾時、鎖、重試與觀測。',
    context: '本站用 cron 討論 Cloudflare Workers、Claude Code scheduled tasks、內容營運與 agent automation。',
    links: [{ label: '站內搜尋 cron', url: '/search?q=cron&mode=rag' }],
  },
  {
    term: 'schema',
    definition: '描述資料欄位、型別、結構與約束的規格。',
    advanced: 'Schema 可以用在資料庫、API、Zod validation、模型結構化輸出與工具參數；一致的 schema 能降低前後端與 AI 工具之間的漂移。',
    context: '本站用 schema 討論 Prisma、Zod、function calling、資料同步與內容 frontmatter。',
    links: [{ label: '站內搜尋 schema', url: '/search?q=schema&mode=rag' }],
  },
  {
    term: 'migration',
    definition: '把資料庫、內容格式或系統設定從舊結構改到新結構的變更流程。',
    advanced: 'Migration 要處理向前/向後相容、資料回填、rollback、部署順序與線上資料一致性；小站也很容易被隱性 schema 變更卡住。',
    context: '本站用 migration 討論 D1、Prisma、Cloudflare、內容模型與部署流程。',
    links: [{ label: '站內搜尋 migration', url: '/search?q=migration&mode=rag' }],
  },
  {
    term: 'cache',
    aliases: ['caching'],
    definition: '把常用結果暫存起來，減少重複計算、查詢或外部 API 呼叫。',
    advanced: 'Cache 設計要處理 key、TTL、invalidation、stale data、權限與一致性；AI 系統還可能快取 embedding、檢索結果或模型回答。',
    context: '本站用 cache 討論 semantic caching、React Query、Cloudflare KV、RAG 成本與效能。',
    links: [{ label: '站內搜尋 cache', url: '/search?q=cache&mode=rag' }],
  },
  {
    term: 'edge computing',
    aliases: ['edge'],
    definition: '把運算放到靠近使用者或資料來源的節點，降低延遲並改善可用性。',
    advanced: 'Edge runtime 通常啟動快、延遲低，但會有 CPU time、檔案系統、native module、binding 與長任務限制。',
    context: '本站用 edge computing 討論 Cloudflare Workers、Astro SSR、D1/R2/KV 與全球部署。',
    links: [{ label: '站內搜尋 edge computing', url: '/search?q=edge%20computing&mode=rag' }],
  },
  {
    term: 'serverless',
    definition: '不用自己管理伺服器的執行模式，由平台按請求或事件啟動程式。',
    advanced: 'Serverless 簡化部署與擴縮，但要理解 cold start、timeout、binding、持久連線、背景任務與平台限制。',
    context: '本站用 serverless 討論 Cloudflare Workers、D1、Astro、cron 與小型產品部署。',
    links: [{ label: '站內搜尋 serverless', url: '/search?q=serverless&mode=rag' }],
  },
  {
    term: 'monorepo',
    definition: '把多個應用、套件或服務放在同一個 Git repository 裡管理。',
    advanced: 'Monorepo 能共享型別、schema 與工具鏈，但要處理 build cache、依賴邊界、CI 範圍與版本發布；Turborepo 是常見工具之一。',
    context: '本站用 monorepo 討論 Turborepo、前後端共用、AI codebase context 與產品開發流程。',
    links: [{ label: '站內搜尋 monorepo', url: '/search?q=monorepo&mode=rag' }],
  },
  {
    term: 'queue',
    aliases: ['job queue'],
    definition: '把工作先放進佇列，再由 worker 逐步處理的架構。',
    advanced: 'Queue 適合背景任務、重試、削峰與長時間工作；設計時要處理 idempotency、dead-letter、併發、優先級與任務可觀測性。',
    context: '本站用 queue 討論 BullMQ、Celery、內容 pipeline、RAG indexing 與背景任務。',
    links: [{ label: '站內搜尋 queue', url: '/search?q=queue&mode=rag' }],
  },
  {
    term: 'knowledge graph',
    aliases: ['GraphRAG'],
    definition: '用節點與關係表示知識，讓系統能追蹤實體之間的連結。',
    advanced: 'Knowledge graph 可用來補足向量搜尋不擅長的多跳關係、實體消歧與全局摘要；GraphRAG 則把圖結構納入檢索與生成流程。',
    context: '本站用 knowledge graph/GraphRAG 討論程式碼理解、RAG 架構與多實體查詢。',
    links: [{ label: '站內搜尋 knowledge graph', url: '/search?q=knowledge%20graph&mode=rag' }],
  },
  {
    term: 'LLM-as-judge',
    aliases: ['LLM as judge', 'self-reflection'],
    definition: '讓另一個模型或同一模型用評審角色檢查答案品質、事實性或是否符合規格。',
    advanced: 'LLM-as-judge 可用於自動評估與反思，但會有偏誤、標準漂移與可重現性問題；重要任務仍要搭配人工標註與固定 eval set。',
    context: '本站用 LLM-as-judge 討論 RAG evaluation、self-reflection、code review 與 agent 自我修正。',
    links: [{ label: '站內搜尋 LLM-as-judge', url: '/search?q=LLM-as-judge&mode=rag' }],
  },
  {
    term: 'multi-query',
    aliases: ['query expansion'],
    definition: '把使用者的一個問題改寫成多個查詢，增加檢索召回不同角度資料的機會。',
    advanced: 'Multi-query 能改善短查詢或模糊查詢，但也可能引入噪音；通常要搭配去重、reranking、RRF 或查詢分類控制。',
    context: '本站用 multi-query/query expansion 討論 advanced RAG、檢索召回與問題改寫。',
    links: [{ label: '站內搜尋 multi-query', url: '/search?q=multi-query&mode=rag' }],
  },
  {
    term: 'query classification',
    aliases: ['adaptive routing'],
    definition: '先判斷使用者問題類型，再決定要走哪種檢索、工具或回答策略。',
    advanced: 'Query classification 可把精確查詢、探索型查詢、比較型查詢、需要工具的查詢分流；分類錯誤會直接影響 RAG 成本與答案品質。',
    context: '本站用 query classification/adaptive routing 討論 RAG router、Text-to-SQL 與多模型路由。',
    links: [{ label: '站內搜尋 query classification', url: '/search?q=query%20classification&mode=rag' }],
  },
  {
    term: 'semantic caching',
    definition: '用語意相似度判斷新問題是否可以重用舊答案或舊檢索結果。',
    advanced: 'Semantic caching 能降低成本與延遲，但要處理相似度門檻、資料過期、權限、個人化上下文與答案是否仍可重用。',
    context: '本站用 semantic caching 討論 RAG 成本優化、embedding、cache key 與產品延遲。',
    links: [{ label: '站內搜尋 semantic caching', url: '/search?q=semantic%20caching&mode=rag' }],
  },
  {
    term: 'KV cache',
    definition: 'Transformer 推理時暫存已處理 token 的 key/value 狀態，避免每次生成都重算全部上下文。',
    advanced: 'KV cache 會隨 context 長度與 batch 增長，占用大量 VRAM/RAM；壓縮、量化與分頁管理會直接影響長上下文推理成本。',
    context: '本站用 KV cache 討論本機推理、TurboQuant、long context、vLLM 與 GPU 記憶體。',
    links: [{ label: '站內搜尋 KV cache', url: '/search?q=KV%20cache&mode=rag' }],
  },
  {
    term: 'LoRA',
    definition: '一種低成本微調方法，只訓練少量額外參數來調整大模型行為。',
    advanced: 'LoRA 能降低 fine-tuning 的顯存與訓練成本，適合任務或風格調整；但資料品質、基礎模型能力與評估仍是成敗關鍵。',
    context: '本站用 LoRA 討論本機模型、小模型、微調與開源 LLM 生態。',
    links: [{ label: '站內搜尋 LoRA', url: '/search?q=LoRA&mode=rag' }],
  },
  {
    term: 'quantization',
    aliases: ['量化'],
    definition: '用較低精度儲存或計算模型權重，降低記憶體和推理成本。',
    advanced: 'Quantization 會在速度、記憶體與品質之間取捨；本機 LLM 常見 Q4、Q5、Q8 等格式，還要看硬體與推理引擎支援。',
    context: '本站用 quantization 討論 GGUF、llama.cpp、Ollama、本機推理與 KV cache 壓縮。',
    links: [{ label: '站內搜尋 quantization', url: '/search?q=quantization&mode=rag' }],
  },
  {
    term: 'model routing',
    aliases: ['multi-model routing'],
    definition: '依任務、成本、速度或品質需求，把請求分配給不同模型。',
    advanced: 'Model routing 可依 query type、難度、延遲、價格、供應商可用性與 fallback 策略決定模型；評估資料不足時很容易只是在增加複雜度。',
    context: '本站用 model routing 討論多模型編排、agent CLI、LLM council、OpenRouter/9Router 與成本控制。',
    links: [{ label: '站內搜尋 model routing', url: '/search?q=model%20routing&mode=rag' }],
  },
  {
    term: 'structured output',
    aliases: ['結構化輸出'],
    definition: '要求模型用固定 schema 輸出 JSON 或其他可解析格式。',
    advanced: 'Structured output 能讓模型結果進入程式流程，但仍要做 schema validation、錯誤修復、版本控制與欄位語意檢查。',
    context: '本站用 structured output 討論 function calling、資料抽取、內容 pipeline、評估與自動化。',
    links: [{ label: '站內搜尋 structured output', url: '/search?q=structured%20output&mode=rag' }],
  },
  {
    term: 'hallucination',
    aliases: ['幻覺', 'hallucinations'],
    definition: '模型一本正經地生成看似合理、實際錯誤或捏造的內容。',
    advanced: 'Hallucination 可分 factuality（與世界知識矛盾）與 faithfulness（與給定上下文矛盾）兩類；緩解手段包含 RAG grounding、citation 檢查、LLM-as-judge 與 abstention（讓模型說不知道）。',
    context: '本站用 hallucination 討論 RAG 品質、agent 可觀測性與評估方法。',
    links: [{ label: '站內搜尋 hallucination', url: '/search?q=hallucination&mode=rag' }],
  },
  {
    term: 'prompt injection',
    aliases: ['提示注入'],
    definition: '把惡意指令藏在模型會讀到的內容裡（網頁、email、文件），讓模型執行攻擊者而非使用者的意圖。',
    advanced: 'LLM 把指令與資料攤平成同一條 token 串流，架構上無法區分兩者，所以 prompt injection 無法靠「把模型調乖」根治，只能靠信任邊界與架構約束（如六大設計模式、CaMeL）緩解。',
    context: '本站用 prompt injection 討論 agent 安全、tool output 信任邊界與資料外洩攻擊鏈。',
    links: [{ label: '站內搜尋 prompt injection', url: '/search?q=prompt%20injection&mode=rag' }],
  },
  {
    term: 'benchmark',
    aliases: ['基準測試'],
    definition: '一組固定的測試題目與評分方式，用來在同一把尺上比較不同模型或系統的能力。',
    advanced: 'Benchmark 要注意資料污染（模型在訓練時看過題目）、與真實任務的落差，以及高分是真能力還是統計捷徑；生產系統通常還需要自建領域 eval。',
    context: '本站用 benchmark 討論模型評估、檢索品質與論文判讀。',
    links: [{ label: '站內搜尋 benchmark', url: '/search?q=benchmark&mode=rag' }],
  },
  {
    term: 'baseline',
    aliases: ['基準線'],
    definition: '比較新方法之前先建立的參照點，通常是最簡單可行的做法或現況系統的表現。',
    advanced: '沒有 baseline 的改進數字無法解讀；好的 baseline 要夠強（例如 BM25 之於檢索），否則「贏過 baseline」只是贏過稻草人。',
    context: '本站用 baseline 討論評估方法、RAG 改進與論文判讀。',
    links: [{ label: '站內搜尋 baseline', url: '/search?q=baseline&mode=rag' }],
  },
  {
    term: 'A/B 測試',
    aliases: ['A/B testing', 'A/B test'],
    definition: '把流量分成兩組，分別跑新舊版本，用統計方法判斷差異是真實效果還是隨機波動。',
    advanced: 'A/B 測試要先決定指標、樣本數與顯著水準；LLM 應用因輸出抖動大，常需要先過離線 eval 再上線上 A/B，並注意多重比較與提早偷看結果的偏誤。',
    context: '本站用 A/B 測試討論 agent 調整的上線階梯與評估方法論。',
    links: [{ label: '站內搜尋 A/B 測試', url: '/search?q=A%2FB%20testing&mode=rag' }],
  },
  {
    term: 'Agentic RAG',
    aliases: ['agentic retrieval'],
    definition: '讓 agent 自主決定何時檢索、查什麼、查幾輪的 RAG 形態，而不是固定的「檢索一次再回答」流程。',
    advanced: 'Agentic RAG 把 retrieval 變成工具呼叫：agent 可以改寫 query、分解問題、跨來源多輪檢索並自我檢查；代價是延遲、成本與失敗模式都更難預測，更需要 eval 與 observability。',
    context: '本站用 Agentic RAG 討論檢索決策、工具選用與 RAG 架構演進。',
    links: [{ label: '站內搜尋 Agentic RAG', url: '/search?q=Agentic%20RAG&mode=rag' }],
  },
  {
    term: 'top-k',
    definition: '從排序結果裡取前 k 名，例如檢索時只拿相似度最高的 k 個 chunk。',
    advanced: 'top-k 的 k 是品質與成本的槓桿：k 太小漏掉相關內容、k 太大稀釋上下文；評估時對應 recall@k / precision@k 等指標。',
    context: '本站用 top-k 討論向量檢索、reranking 與 RAG 參數調校。',
    links: [{ label: '站內搜尋 top-k', url: '/search?q=top-k&mode=rag' }],
  },
  {
    term: 'OpenTelemetry',
    aliases: ['OTel'],
    definition: '開源的可觀測性標準，統一 trace、metrics、logs 的格式與收集方式，避免被特定監控廠商綁死。',
    advanced: 'OpenTelemetry 的 GenAI 語義約定把 LLM call、tool call、agent step 標準化成 span 屬性；Datadog、Langfuse、Phoenix 等工具都建立在這層之上，但截至 v1.41.x 仍在 beta。',
    context: '本站用 OpenTelemetry 討論 agent 可觀測性與故障偵測。',
    links: [{ label: '站內搜尋 OpenTelemetry', url: '/search?q=OpenTelemetry&mode=rag' }],
  },
  {
    term: 'faithfulness',
    aliases: ['忠實度'],
    definition: '衡量模型答案是否忠於給定的上下文，沒有自行添加或扭曲資訊。',
    advanced: 'Faithfulness 是 RAG 評估的核心指標之一（RAGAS 等框架內建）：答案可以事實正確但不忠實（內容不在檢索結果裡），也可以忠實但錯誤（檢索到錯的資料），兩者要分開量測。',
    context: '本站用 faithfulness 討論 RAG 雙層指標與 LLM-as-judge 評估。',
    links: [{ label: '站內搜尋 faithfulness', url: '/search?q=faithfulness&mode=rag' }],
  },
  {
    term: 'RL',
    aliases: ['reinforcement learning', '強化學習'],
    definition: '讓模型透過嘗試與回饋（reward）學習策略的訓練方法，而不是直接給標準答案。',
    advanced: 'RL 在 LLM 領域常見於 RLHF、GRPO 等後訓練方法；reward 稀疏、credit assignment 困難是主要痛點，這也是 GEPA 等語言反思方法主打樣本效率的原因。',
    context: '本站用 RL 討論模型後訓練、prompt 自動優化與 agent 行為塑形。',
    links: [{ label: '站內搜尋 reinforcement learning', url: '/search?q=reinforcement%20learning&mode=rag' }],
  },
  {
    term: 'arXiv',
    definition: '免費的學術論文預印本平台，AI 領域絕大多數論文都先發表在這裡，不經同儕審查。',
    advanced: 'arXiv 編號（如 2508.21038）代表年月與流水號；因為沒有審查，讀 arXiv 論文要自己檢查 baseline 強度、資料污染與宣稱是否過頭。',
    context: '本站引用論文時多以 arXiv 編號標註來源。',
    links: [{ label: '站內搜尋 arXiv', url: '/search?q=arXiv&mode=rag' }],
  },
  {
    term: 'Langfuse',
    definition: '開源的 LLM 應用可觀測性平台，記錄 prompt、completion、成本與延遲，支援自架。',
    advanced: 'Langfuse 建立在 OpenTelemetry 相容的 trace 模型上，提供 session 重放、評分標註與 prompt 管理；與 LangSmith 的主要差異是開源可自架。',
    context: '本站用 Langfuse 討論 agent 觀測、token 成本追蹤與評估流程。',
    links: [{ label: '站內搜尋 Langfuse', url: '/search?q=Langfuse&mode=rag' }],
  },
  {
    term: 'LangSmith',
    definition: 'LangChain 官方的 LLM 應用觀測與評估平台，追蹤每次呼叫的輸入輸出並支援資料集評測。',
    advanced: 'LangSmith 與 LangChain/LangGraph 深度整合，提供 trace 視覺化、prompt playground 與 eval pipeline；非 LangChain 應用也能透過 SDK 接入，但閉源、SaaS 為主。',
    context: '本站用 LangSmith 討論 agent 觀測與評估工具選型。',
    links: [{ label: '站內搜尋 LangSmith', url: '/search?q=LangSmith&mode=rag' }],
  },
]

export function normalizeGlossaryTerms(entries: GlossaryEntry[]): GlossaryEntry[] {
  const seen = new Set<string>()
  return entries.filter((entry) => {
    const key = entry.term.trim().toLowerCase()
    if (!key || seen.has(key)) return false
    seen.add(key)
    return true
  })
}

export function findDefaultGlossaryEntry(term: string): GlossaryEntry | undefined {
  const normalized = term.trim().toLowerCase()
  return DEFAULT_GLOSSARY_TERMS.find((entry) => {
    if (entry.term.toLowerCase() === normalized) return true
    return entry.aliases?.some((alias) => alias.toLowerCase() === normalized)
  })
}
