import type { PipelineDefinition } from './types'

export const pipelineDefinitions: PipelineDefinition[] = [
  {
    id: 'content-ops',
    title: 'Content Ops Agent',
    description: 'Generate or review the content operations report.',
    category: 'ops',
    risk: 'low',
    runtime: 'worker',
    inputs: [],
    tools: ['run_content_ops', 'write_artifact'],
    stages: [
      { id: 'run-content-ops', title: 'Run content ops report', kind: 'module', tool: 'run_content_ops' },
      { id: 'write-report-artifact', title: 'Write report artifact', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [{ id: 'content-ops-report', type: 'json_report', title: 'Content ops report' }],
    guards: ['admin_required', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 120_000, maxExternalCalls: 0 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
  {
    id: 'post-quality',
    title: 'Quality Agent',
    description: 'Run deterministic post quality and reference checks for a markdown post or directory.',
    category: 'production',
    risk: 'low',
    runtime: 'worker',
    inputs: [
      {
        id: 'slug',
        label: 'Post slug',
        type: 'string',
        required: false,
        placeholder: 'ai/2026-05-10-example',
      },
    ],
    tools: ['read_post_content', 'run_post_quality_check', 'run_reference_check', 'write_artifact'],
    stages: [
      { id: 'quality-check', title: 'Run post quality check', kind: 'module', tool: 'run_post_quality_check' },
      { id: 'reference-check', title: 'Run reference check', kind: 'module', tool: 'run_reference_check' },
      { id: 'quality-evaluation', title: 'Run LLM quality evaluation', kind: 'llm' },
      { id: 'quality-report', title: 'Write quality report', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [
      { id: 'quality-report', type: 'json_report', title: 'Quality report' },
      { id: 'quality-evaluation', type: 'json_report', title: 'Quality evaluation' },
    ],
    guards: ['admin_required', 'post_path', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 120_000, maxExternalCalls: 1 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
  {
    id: 'embed-sync',
    title: 'Embedding Agent',
    description: 'Run one embed batch and record the result in the admin job timeline.',
    category: 'knowledge',
    risk: 'medium',
    runtime: 'worker',
    inputs: [
      { id: 'sources', label: 'Sources JSON', type: 'json', defaultValue: ['posts', 'docs'] },
      { id: 'offset', label: 'Offset', type: 'number', defaultValue: 0 },
      { id: 'limit', label: 'Limit', type: 'number', defaultValue: 50 },
    ],
    tools: ['run_embed_sync', 'write_artifact'],
    stages: [
      { id: 'embed-sync', title: 'Run embed batch', kind: 'api', tool: 'run_embed_sync' },
      { id: 'embed-report', title: 'Write embed result artifact', kind: 'api', tool: 'write_artifact' },
    ],
    artifacts: [{ id: 'embed-sync-result', type: 'json_report', title: 'Embed sync result' }],
    guards: ['admin_required', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 2, maxRuntimeMs: 600_000, maxExternalCalls: 1 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
  {
    id: 'crawl-sync',
    title: 'Crawl Agent',
    description: 'Track crawl sync as a harness job. Record crawl sync requests in the harness while execution stays on the Worker endpoint with CRAWL_SECRET validation.',
    category: 'knowledge',
    risk: 'medium',
    runtime: 'worker',
    inputs: [
      { id: 'full', label: 'Full crawl', type: 'boolean', defaultValue: false },
      { id: 'modifiedSince', label: 'Modified since', type: 'number' },
    ],
    tools: ['run_crawl_sync', 'write_artifact'],
    stages: [
      { id: 'crawl-sync', title: 'Create crawl sync job record', kind: 'api', tool: 'run_crawl_sync' },
      { id: 'crawl-report', title: 'Write crawl request artifact', kind: 'api', tool: 'write_artifact' },
    ],
    artifacts: [{ id: 'crawl-sync-record', type: 'json_report', title: 'Crawl sync job record' }],
    guards: ['admin_required', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 2, maxRuntimeMs: 600_000, maxExternalCalls: 1 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: true,
  },
  {
    id: 'translation',
    title: 'Translation Agent',
    description: 'Translate a zh-TW post to en draft. Creates draft markdown with lang: en.',
    category: 'production',
    risk: 'high',
    runtime: 'worker',
    inputs: [
      {
        id: 'slug',
        label: 'Source post slug',
        type: 'string',
        required: true,
        placeholder: 'ai/2026-05-10-example',
      },
    ],
    tools: ['read_post_content', 'write_draft_artifact', 'run_post_quality_check', 'run_reference_check', 'write_artifact'],
    stages: [
      { id: 'read-source', title: 'Read source post', kind: 'module', tool: 'read_post_content' },
      { id: 'translate', title: 'Translate content', kind: 'llm', tool: 'write_draft_artifact' },
      { id: 'cultural-review', title: 'Cultural review', kind: 'llm' },
      { id: 'native-check', title: 'Native checker', kind: 'llm' },
      { id: 'quality-check', title: 'Run quality check', kind: 'module', tool: 'run_post_quality_check' },
      { id: 'reference-check', title: 'Run reference check', kind: 'module', tool: 'run_reference_check' },
      { id: 'review-gate', title: 'Publish review gate', kind: 'human_review' },
      { id: 'write-draft', title: 'Write draft artifact', kind: 'module', tool: 'write_draft_artifact' },
      { id: 'translation-report', title: 'Write translation report', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [
      { id: 'translation-draft', type: 'markdown_draft', title: 'English draft' },
      { id: 'translation-report', type: 'json_report', title: 'Translation report' },
    ],
    guards: ['admin_required', 'draft_only', 'reviewer_never_auto_fix', 'no_fabrication', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 1_200_000, maxExternalCalls: 3 },
    requiresAdmin: true,
    writesMarkdown: true,
    usesExternalResearch: false,
  },
  {
    id: 'research-brief',
    title: 'Research Brief Agent',
    description: 'Generate a claim-oriented research brief and draft outline for topic-first content workflows.',
    category: 'knowledge',
    risk: 'high',
    runtime: 'worker',
    inputs: [
      {
        id: 'topic',
        label: 'Research topic',
        type: 'string',
        required: true,
        placeholder: 'Cloudflare Workers on Edge AI',
      },
      {
        id: 'language',
        label: 'Language',
        type: 'string',
        defaultValue: 'zh-TW',
        options: ['zh-TW', 'en'],
      },
      {
        id: 'researchDepth',
        label: 'Research depth',
        type: 'string',
        defaultValue: 'standard',
        options: ['quick', 'standard', 'deep'],
      },
      {
        id: 'includeExternalSources',
        label: 'Include external source suggestions',
        type: 'boolean',
        defaultValue: true,
      },
    ],
    tools: ['write_draft_artifact', 'run_post_quality_check', 'run_reference_check', 'write_artifact'],
    stages: [
      { id: 'research-brief', title: 'Generate research brief', kind: 'llm' },
      { id: 'research-quality', title: 'Run research draft quality check', kind: 'module', tool: 'run_post_quality_check' },
      { id: 'research-reference', title: 'Run research draft reference check', kind: 'module', tool: 'run_reference_check' },
      { id: 'research-review', title: 'Research review gate', kind: 'human_review' },
      { id: 'research-write-draft', title: 'Write research draft markdown', kind: 'module', tool: 'write_draft_artifact' },
      { id: 'research-report', title: 'Write research brief artifact', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [
      { id: 'research-brief-draft', type: 'markdown_draft', title: 'Research brief draft markdown' },
      { id: 'research-brief-report', type: 'json_report', title: 'Research brief report' },
    ],
    guards: ['admin_required', 'reviewer_never_auto_fix', 'no_fabrication', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 0, maxRuntimeMs: 360_000, maxExternalCalls: 1 },
    requiresAdmin: true,
    writesMarkdown: true,
    usesExternalResearch: false,
  },
  {
    id: 'youtube-brief',
    title: 'YouTube Brief Agent',
    description: 'Build a YouTube-to-post brief skeleton for manual completion. Tries to enrich with oEmbed and public timed-text metadata.',
    category: 'knowledge',
    risk: 'high',
    runtime: 'worker',
    inputs: [
      {
        id: 'videoUrl',
        label: 'YouTube URL',
        type: 'string',
        required: true,
        placeholder: 'https://www.youtube.com/watch?v=xxxxxxxxxxx',
      },
      {
        id: 'language',
        label: 'Language',
        type: 'string',
        defaultValue: 'zh-TW',
        options: ['zh-TW', 'en'],
      },
      {
        id: 'includeTranscript',
        label: 'Include transcript preview',
        type: 'boolean',
        defaultValue: true,
      },
    ],
    tools: ['write_draft_artifact', 'run_post_quality_check', 'run_reference_check', 'write_artifact'],
    stages: [
      { id: 'youtube-brief', title: 'Build YouTube brief skeleton', kind: 'module' },
      { id: 'youtube-quality', title: 'Run YouTube draft quality check', kind: 'module', tool: 'run_post_quality_check' },
      { id: 'youtube-reference', title: 'Run YouTube draft reference check', kind: 'module', tool: 'run_reference_check' },
      { id: 'youtube-review', title: 'YouTube review gate', kind: 'human_review' },
      { id: 'youtube-write-draft', title: 'Write YouTube draft markdown', kind: 'module', tool: 'write_draft_artifact' },
      { id: 'youtube-report', title: 'Write YouTube brief artifact', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [
      { id: 'youtube-brief-draft', type: 'markdown_draft', title: 'YouTube draft markdown' },
      { id: 'youtube-brief-report', type: 'json_report', title: 'YouTube brief report' },
    ],
    guards: ['admin_required', 'reviewer_never_auto_fix', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 0, maxRuntimeMs: 280_000, maxExternalCalls: 2 },
    requiresAdmin: true,
    writesMarkdown: true,
    usesExternalResearch: false,
  },
  {
    id: 'glossary-gap',
    title: 'Glossary Gap Agent',
    description: 'Identify high-frequency glossary lookup terms and suggest content update opportunities.',
    category: 'maintenance',
    risk: 'medium',
    runtime: 'worker',
    inputs: [
      {
        id: 'days',
        label: 'Lookback days',
        type: 'number',
        defaultValue: 14,
      },
      {
        id: 'minLookupCount',
        label: 'Min total lookup count',
        type: 'number',
        defaultValue: 3,
      },
      {
        id: 'topTerms',
        label: 'Top terms',
        type: 'number',
        defaultValue: 20,
      },
      {
        id: 'topPostsPerTerm',
        label: 'Top posts per term',
        type: 'number',
        defaultValue: 5,
      },
    ],
    tools: ['read_glossary_stats', 'read_post_content', 'write_artifact'],
    stages: [
      { id: 'glossary-gap-scan', title: 'Scan glossary lookup stats', kind: 'module', tool: 'read_glossary_stats' },
      { id: 'glossary-gap-report', title: 'Write glossary gap report', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [{ id: 'glossary-gap-report', type: 'json_report', title: 'Glossary gap report' }],
    guards: ['admin_required', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 180_000, maxExternalCalls: 0 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
  {
    id: 'freshness-review',
    title: 'Freshness Review Agent',
    description: 'Detect stale or high-risk posts and generate weekly refresh tasks.',
    category: 'maintenance',
    risk: 'high',
    runtime: 'worker',
    inputs: [
      {
        id: 'maxAgeDays',
        label: 'Max age in days',
        type: 'number',
        defaultValue: 365,
      },
      {
        id: 'riskThreshold',
        label: 'Risk threshold',
        type: 'number',
        defaultValue: 40,
      },
      {
        id: 'categoryFilter',
        label: 'Category filter (comma separated)',
        type: 'string',
        defaultValue: '',
      },
      {
        id: 'languageFilter',
        label: 'Language filter (comma separated)',
        type: 'string',
        defaultValue: '',
      },
    ],
    tools: ['read_post_content', 'write_artifact'],
    stages: [
      { id: 'freshness-scan', title: 'Scan posts for freshness risk', kind: 'module', tool: 'read_post_content' },
      { id: 'freshness-report', title: 'Write freshness review report', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [{ id: 'freshness-review-report', type: 'json_report', title: 'Freshness review report' }],
    guards: ['admin_required', 'draft_only', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 180_000, maxExternalCalls: 0 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
  {
    id: 'series-suggestions',
    title: 'Series Suggestions Agent',
    description: 'Identify posts that can form coherent series for editorial workflow planning.',
    category: 'maintenance',
    risk: 'medium',
    runtime: 'worker',
    inputs: [
      {
        id: 'topSeriesCount',
        label: 'Top series suggestions',
        type: 'number',
        defaultValue: 12,
      },
      {
        id: 'minPostsPerSeries',
        label: 'Min posts per series',
        type: 'number',
        defaultValue: 2,
      },
      {
        id: 'maxPostsPerSeries',
        label: 'Max posts listed per series',
        type: 'number',
        defaultValue: 8,
      },
      {
        id: 'minSignalLength',
        label: 'Minimum signal length',
        type: 'number',
        defaultValue: 2,
      },
    ],
    tools: ['read_post_content', 'write_artifact'],
    stages: [
      { id: 'series-scan', title: 'Scan post signals', kind: 'module', tool: 'read_post_content' },
      { id: 'series-report', title: 'Write series suggestion report', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [{ id: 'series-suggestions-report', type: 'json_report', title: 'Series suggestion report' }],
    guards: ['admin_required', 'draft_only', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 240_000, maxExternalCalls: 0 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
  {
    id: 'knowledge-graph-prototype',
    title: 'Knowledge Graph Prototype Agent',
    description: 'Build a minimal entity co-occurrence snapshot from tags and topic signals.',
    category: 'maintenance',
    risk: 'medium',
    runtime: 'worker',
    inputs: [
      {
        id: 'minEntityFrequency',
        label: 'Min entity frequency',
        type: 'number',
        defaultValue: 2,
      },
      {
        id: 'topNodes',
        label: 'Top nodes',
        type: 'number',
        defaultValue: 80,
      },
      {
        id: 'minCoOccurrence',
        label: 'Min co-occurrence for edge',
        type: 'number',
        defaultValue: 2,
      },
      {
        id: 'topEdges',
        label: 'Top edges',
        type: 'number',
        defaultValue: 180,
      },
    ],
    tools: ['read_post_content', 'write_artifact'],
    stages: [
      { id: 'knowledge-graph-scan', title: 'Build knowledge graph snapshot', kind: 'module', tool: 'read_post_content' },
      { id: 'knowledge-graph-report', title: 'Write graph report', kind: 'module', tool: 'write_artifact' },
    ],
    artifacts: [{ id: 'knowledge-graph-report', type: 'json_report', title: 'Knowledge graph prototype report' }],
    guards: ['admin_required', 'draft_only', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 240_000, maxExternalCalls: 0 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
  {
    id: 'metadata-suggestions',
    title: 'Metadata Agent',
    description: 'Generate metadata suggestions for one post.',
    category: 'production',
    risk: 'medium',
    runtime: 'worker',
    inputs: [
      {
        id: 'slug',
        label: 'Post slug',
        type: 'string',
        required: true,
        placeholder: 'ai/2026-05-10-example',
      },
    ],
    tools: ['read_post_content', 'write_artifact'],
    stages: [
      { id: 'read-post', title: 'Read source post', kind: 'module', tool: 'read_post_content' },
      { id: 'metadata-suggestion', title: 'Generate metadata suggestion', kind: 'module', tool: 'write_artifact' },
      { id: 'metadata-suggestion-evaluation', title: 'Review metadata suggestion', kind: 'llm' },
    ],
    artifacts: [
      { id: 'metadata-suggestion-report', type: 'json_report', title: 'Metadata suggestions' },
      { id: 'metadata-suggestion-evaluation', type: 'json_report', title: 'Metadata suggestion evaluation' },
    ],
    guards: ['admin_required', 'draft_only', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 180_000, maxExternalCalls: 1 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
  {
    id: 'internal-links',
    title: 'Internal Link Agent',
    description: 'Generate internal link suggestions for one post.',
    category: 'production',
    risk: 'medium',
    runtime: 'worker',
    inputs: [
      {
        id: 'slug',
        label: 'Post slug',
        type: 'string',
        required: true,
        placeholder: 'ai/2026-05-10-example',
      },
    ],
    tools: ['read_post_content', 'run_content_ops', 'write_artifact'],
    stages: [
      { id: 'read-post', title: 'Read source post', kind: 'module', tool: 'read_post_content' },
      { id: 'run-content-ops', title: 'Run content ops helper', kind: 'module', tool: 'run_content_ops' },
      { id: 'link-report', title: 'Write link opportunities', kind: 'module', tool: 'write_artifact' },
      { id: 'internal-link-evaluation', title: 'Review internal link suggestions', kind: 'llm' },
    ],
    artifacts: [
      { id: 'internal-links-report', type: 'json_report', title: 'Internal link opportunities' },
      { id: 'internal-link-evaluation', type: 'json_report', title: 'Internal link evaluation' },
    ],
    guards: ['admin_required', 'tool_allowlist', 'budget_limit'],
    budget: { maxRetries: 1, maxRuntimeMs: 180_000, maxExternalCalls: 1 },
    requiresAdmin: true,
    writesMarkdown: false,
    usesExternalResearch: false,
  },
]

export function listPipelines(): PipelineDefinition[] {
  return pipelineDefinitions
}

export function getPipelineDefinition(id: string): PipelineDefinition | undefined {
  return pipelineDefinitions.find((pipeline) => pipeline.id === id)
}
