import { env as workerEnv } from 'cloudflare:workers'

export interface AgentQueueMessage {
  agentId: string
  input?: Record<string, unknown>
  parentRunId?: string
}

export interface Env {
  DB: D1Database
  SESSION: KVNamespace
  RATE: KVNamespace
  DEEP_RESEARCH_KV?: KVNamespace
  VECTORIZE_INDEX: VectorizeIndex
  VECTORIZE_ABSTRACT?: VectorizeIndex
  AI: Ai
  R2_IMAGES: R2Bucket
  CRAWL_SECRET?: string
  ADMIN_PASSWORD?: string
  LLM_PROVIDER?: string
  URL?: string
  AGENT_QUEUE?: Queue<AgentQueueMessage>
  R2_AGENT_MEMORY?: R2Bucket
  R2_AGENT_ARTIFACT?: R2Bucket
  AGENT_OS_ENABLED?: string
  AGENT_OS_PLANNER?: string
  AGENT_OS_RESEARCH?: string
  AGENT_OS_WRITER?: string
  AGENT_OS_CRITIC?: string
  AGENT_OS_MEMORY_R2?: string
  AGENT_OS_TOOLS_MCP_EXTERNAL?: string
  AGENT_OS_SCHEDULER_QUEUES?: string
  // agent-evidence
  AGENT_EVIDENCE_ENABLED?: string
  // agent-console
  AGENT_CONSOLE_ENABLED?: string
  AGENT_CONSOLE_RBAC?: string
  AGENT_CONSOLE_COST_DASHBOARD?: string
  AGENT_CONSOLE_FLOW_EDITOR?: string
  // agent-artifact
  AGENT_ARTIFACT_ENABLED?: string
  AGENT_ARTIFACT_R2_OFFLOAD?: string
  AGENT_ARTIFACT_CSV?: string
  AGENT_ARTIFACT_PDF?: string
  AGENT_ARTIFACT_PPTX?: string
  AGENT_ARTIFACT_NOTION?: string
  AGENT_ARTIFACT_SLACK?: string
  AGENT_ARTIFACT_GITHUB_ISSUE?: string
  AGENT_ARTIFACT_GITHUB_PR?: string
  AGENT_ARTIFACT_EMAIL?: string
  // agent-providers
  AGENT_PROVIDERS_ENABLED?: string
  AGENT_PROVIDERS_LLM_OPENAI?: string
  AGENT_PROVIDERS_LLM_ANTHROPIC?: string
  AGENT_PROVIDERS_LLM_GEMINI?: string
  AGENT_PROVIDERS_LLM_GROQ?: string
  AGENT_PROVIDERS_LLM_OPENROUTER?: string
  AGENT_PROVIDERS_SEARCH_TAVILY?: string
  AGENT_PROVIDERS_SEARCH_EXA?: string
  AGENT_PROVIDERS_SEARCH_JINA?: string
  AGENT_PROVIDERS_READER_JINA?: string
  AGENT_PROVIDERS_READER_FIRECRAWL?: string
  AGENT_PROVIDERS_READER_BROWSER?: string
  AGENT_PROVIDERS_READER_DIRECT_FETCH?: string
  AGENT_PROVIDERS_KNOWLEDGE_NOTION?: string
  AGENT_PROVIDERS_KNOWLEDGE_GITHUB?: string
  AGENT_PROVIDERS_KNOWLEDGE_DRIVE?: string
  AGENT_PROVIDERS_KNOWLEDGE_SQL?: string
  AGENT_PROVIDERS_ACTION_GITHUB_ISSUE?: string
  AGENT_PROVIDERS_ACTION_GITHUB_COMMENT?: string
  AGENT_PROVIDERS_ACTION_SLACK?: string
  AGENT_PROVIDERS_ACTION_NOTION?: string
  AGENT_PROVIDERS_ACTION_EMAIL?: string
  AGENT_PROVIDERS_ROUTING_FALLBACK?: string
  AGENT_PROVIDERS_ROUTING_HEALTH_CHECKS?: string
  AGENT_PROVIDERS_ROUTING_LOAD_BALANCE?: string
  AGENT_PROVIDERS_ROUTING_RATE_LIMITS?: string
  // agent-policy
  AGENT_POLICY_ENABLED?: string
  AGENT_POLICY_BUDGET_ENFORCE?: string
  AGENT_POLICY_PROVIDER_ENFORCE?: string
  AGENT_POLICY_QUALITY_ENFORCE?: string
  AGENT_POLICY_SECURITY_ENFORCE?: string
  AGENT_POLICY_HUMAN_GATES?: string
  // agent-flow
  AGENT_FLOW_ENABLED?: string
  AGENT_FLOW_DURABLE_EXECUTION?: string
  AGENT_FLOW_DEEP_RESEARCH?: string
  // agent-pipelines-unify
  PIPELINES_PORTED_TO_FLOW?: string
  ADMIN_PIPELINES_REDIRECT_TO_FLOW?: string
  ADMIN_JOBS_WRITES_ENABLED?: string
  PIPELINE_CONTENT_OPS_USE_FLOW?: string
  PIPELINE_POST_QUALITY_USE_FLOW?: string
  PIPELINE_EMBED_SYNC_USE_FLOW?: string
  PIPELINE_CRAWL_SYNC_USE_FLOW?: string
  PIPELINE_TRANSLATION_USE_FLOW?: string
  PIPELINE_RESEARCH_BRIEF_USE_FLOW?: string
  PIPELINE_ARXIV_READING_USE_FLOW?: string
  PIPELINE_YOUTUBE_BRIEF_USE_FLOW?: string
  PIPELINE_GLOSSARY_GAP_USE_FLOW?: string
  PIPELINE_FRESHNESS_REVIEW_USE_FLOW?: string
  PIPELINE_SERIES_SUGGESTIONS_USE_FLOW?: string
  PIPELINE_KNOWLEDGE_GRAPH_PROTOTYPE_USE_FLOW?: string
  PIPELINE_METADATA_SUGGESTIONS_USE_FLOW?: string
  PIPELINE_INTERNAL_LINKS_USE_FLOW?: string
}

export function getEnv(): Env {
  return workerEnv as unknown as Env
}
